---
title: "Forecasting_Fraud"
output: html_document
date: "2026-07-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#Install it if you haven't.
library(guardianapi)
```

```{r}
#Enter your Guardian API key.
gu_api_key()
```

```{r}
#Find contents with required keywords and period.
fraud <- gu_content(query = '"fraud" AND ("UK" OR "United Kingdom")', from_date = "1999-01-01",
                            to_date = "2024-12-31")
```

```{r}
#Find contents for comparing with forecasts.
fraud1 <- gu_content(query = '"fraud" AND ("UK" OR "United Kingdom")', from_date = "2025-01-01",
                            to_date = "2025-12-31")
```

```{r}
#Inspect the articles obtained.
tibble::glimpse(fraud)
```

# Inspect the contents:

```{r}
table(fraud$type)
```

```{r}
table(fraud$pillar_name)
```

```{r}
table(fraud$production_office)#All English-speaking countries so all contents are in English.
```

```{r}
library(tidyverse)
fraud %>%
  filter(pillar_name == "Sport") %>%
  select(web_title, web_publication_date) %>%
  head(20)
```

```{r}
library(tidyverse)
fraud %>%
  filter(pillar_name == "Arts") %>%
  select(web_title, web_publication_date) %>%
  head(20)
```

```{r}
fraud %>%
  filter(type == "liveblog") %>%
  select(web_title, web_publication_date) %>%
  head(20)
```

```{r}
fraud %>%
  filter(type == "article") %>%
  select(web_title, web_publication_date) %>%
  head(20)
```

```{r}
#Collect only contents with type "article" and pillar name "Lifestyle"/"News"/"Opinion".
fraud %>%
  filter(type == "article" & pillar_name %in% c("Lifestyle","News","Opinion")) %>%
  select(web_title, web_publication_date) %>%
  head(20)
```

# Count the number of articles published each month

```{r}
library(dplyr)
library(lubridate)

monthly_fraud <- fraud %>%
  filter(type == "article",
         pillar_name %in% c("Lifestyle", "News", "Opinion")) %>%
  mutate(month = floor_date(as.Date(web_publication_date), unit = "month")) %>%
  count(month, name = "n_articles")

monthly_fraud

# Save to a csv
write.csv(monthly_fraud,
          file = "fraud_train.csv",
          row.names = FALSE)
```

```{r}
# Also for the tested contents.
monthly_fraud1 <- fraud1 %>%
  filter(type == "article",
         pillar_name %in% c("Lifestyle", "News", "Opinion")) %>%
  mutate(month = floor_date(as.Date(web_publication_date), unit = "month")) %>%
  count(month, name = "n_articles")

monthly_fraud1

# Save to a csv
write.csv(monthly_fraud1,
          file = "fraud_test.csv",
          row.names = FALSE)
```

# Import fraud and macroeconomic data (treat n_articles as fraud)

```{r}
# Import the training dataset
train <- read.csv("fraud&macroeconomic_train.csv")
View(train)

# Import the testing dataset
test <- read.csv("fraud&macroeconomic_test.csv")
View(test)
```

```{r}
# Name each time series
fraud <- train$fraud
inflation <- train$CPIH
unemployment <- train$unemployment
interest <- train$interest_rate
production <- train$index_of_production_and_industry_sectors
confidence <- train$composite_consumer_confidence
```

# Cross-correlation analysis to find the lead-lag relationships between variables

```{r}
# Test the stationarity of all time series.
library(tseries)

adf.test(fraud)
adf.test(inflation)
adf.test(unemployment)
adf.test(interest)
adf.test(production)
adf.test(confidence)
```

```{r}
# Take first order differencing to check if non-stationary time series become stationary.
adf.test(diff(unemployment))
adf.test(diff(interest))
adf.test(diff(production))
```

```{r}
#Print cross-correlation functions
ccf(fraud, inflation)
ccf(fraud, diff(unemployment))
ccf(fraud, diff(interest))
ccf(fraud, diff(production))
ccf(fraud, confidence)
#Print cross-correlation values
ccf(fraud, inflation, plot = FALSE)
ccf(fraud, diff(unemployment), plot = FALSE)
ccf(fraud, diff(interest), plot = FALSE)
ccf(fraud, diff(production), plot = FALSE)
ccf(fraud, confidence, plot = FALSE)
```

```{r}
ccf(inflation, diff(unemployment))
ccf(inflation, diff(interest))
ccf(inflation, diff(production))
ccf(inflation, confidence)
ccf(inflation, diff(unemployment), plot = FALSE)
ccf(inflation, diff(interest), plot = FALSE)
ccf(inflation, diff(production), plot = FALSE)
ccf(inflation, confidence, plot = FALSE)
```

```{r}
ccf(diff(unemployment), diff(interest))
ccf(diff(unemployment), diff(production))
ccf(diff(unemployment), confidence)
ccf(diff(unemployment), diff(interest), plot = FALSE)
ccf(diff(unemployment), diff(production), plot = FALSE)
ccf(diff(unemployment), confidence, plot = FALSE)
```

```{r}
ccf(diff(interest), diff(production))
ccf(diff(interest), confidence)
ccf(diff(interest), diff(production), plot = FALSE)
ccf(diff(interest), confidence, plot = FALSE)
```

```{r}
ccf(diff(production), confidence)
ccf(diff(production), confidence, plot = FALSE)
```

# Simple linear regression models to understand the linear relationships between variables

```{r}
summary(lm(fraud ~ inflation))
summary(lm(fraud ~ unemployment))
summary(lm(fraud ~ interest))
summary(lm(fraud ~ production))
summary(lm(fraud ~ confidence))
```

```{r}
summary(lm(inflation ~ unemployment))
summary(lm(inflation ~ interest))
summary(lm(inflation ~ production))
summary(lm(inflation ~ confidence))
```

```{r}
summary(lm(unemployment ~ interest))
summary(lm(unemployment ~ production))
summary(lm(unemployment ~ confidence))
```

```{r}
summary(lm(interest ~ production))
summary(lm(interest ~ confidence))
```

```{r}
summary(lm(production ~ confidence))
```

